version: '3.9'
services:
  backend:

    container_name: nestjs_app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: 01690174357Dsa
      DATABASE_NAME: documents_db
    volumes:
      -.:/usr/src/app
      -/usr/src/app/node_modules
    command: npm run start:dev
  
postgres:
  image: postgres:15
  container_name: postgres_container
  restart: always
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: 01690174357Dsa
    POSTGRES_DB: documents_db
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: